apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-driven-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-driven-arc
  template:
      metadata:
        labels:
          app: event-driven-arc
      spec:
        containers:
        - name: event-driven-arc
          image: gcr.io/mimetic-parity-378803/event_driven_architecture:latest